Parameters:
  VPCCIDRBlock:
    Description: VPC CidrBlock
    Type: String
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VPCCIDRBlock

Outputs:
  VPCID:
    Description: "ID da VPC"
    Value: !Ref VPC