Resources:
  WebInstance:
    Type: "AWS::EC2::Instance"
    DeletionPolicy: Retain
    Properties:
      ImageId: ami-07d9160fa81ccffb5
      InstanceType: t3a.micro

  EBSVolume:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    Properties:
      AvailabilityZone: eu-west-1a
      Size: 1
      VolumeType: gp2