Resources:
  WebInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      KeyName: Augusto-Devopslabs
      ImageId: ami-07d9160fa81ccffb5
      InstanceType: t3a.micro
      SecurityGroups:
        - Ref: HTTPSecurityGroup
        - Ref: SSHSecurityGroup
      UserData: 
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            yum update -y
            yum install httpd -y
            service httpd start
            chkconfig httpd on
            echo "Web Server Devops-Labs" > /var/www/html/index.html   
      Tags:
        - Key: Name
          Value: WebInstance
        - Key: Projeto
          Value: Devops-Labs

  EIP:
    Type: "AWS::EC2::EIP"
    Properties:
      InstanceId: 
        Ref: WebInstance

  HTTPSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: HTTP security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SG-WebServerHTTP
        - Key: Projeto
          Value: Devops-Labs

  SSHSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SG-WebServerSSH
        - Key: Projeto
          Value: Devops-Labs